### ISSUE TITLE
Data retention between sessions

### ISSUE THREAD

**Issue by drewdrew122** [racerecords/RaceRecords#16]
The system should have the ability to retain certain data entry values between sessions and groups as these values will not change much during the event.  Possible fields that fit this criteria are the date, region, track, weather, calibration time, etc....

**Comment by mcmillanator** [comment]
I need to make sure I understand the definition of session and group.
With the current PDF being used would you have multiple PDFs per session?
Would you have multiple groups per session?

**Comment by drewdrew122** [comment]
So it breaks down like this.   One event will have multiple groups.  Each group will have multiple sessions

Event -> Group -> Session

ex Event (Regional race event on some weekend) -> Group (1 through 10 for the different car classes) -> Session (two qualifying and one race).

So 1 Event times 10 groups times 3 sessions equals 30 total sessions for the weekend.  Which means 30 separate pdf documents will be created and saved for the weekend.

The data that would be saved between the sessions would be things like the event name, race track, event date, meter calibration time, etc.....  list to be determined,

**Comment by mcmillanator** [comment]
OK.  I'll include something for organizing the data in this way for the MVP.  It'll function, but the UX is going to be terrible and we can work on UX improvements later.

**Comment by drewdrew122** [comment]
So I found an entry list from one of last years events.  You can see that it is broken up into nine different race groups.  Each group has a different set of cars and drivers.  Each group will have two qualifying sessions and one race session (but don't hard code the system to that because it could change or we could have a special event like another enduro)

Click on the Entry List document or the Program document.

https://drive.google.com/drive/folders/1YoKWKNl3CCENpMxVvtjlJYQu-_RuDKo-

**Comment by mcmillanator** [comment]
This changes the scope of what I originally had in mind.  Not a big deal, but I will be starting over in Rails.  Rails will allow me to easily include this requirement from the ground up and make rapid changes.  I might return to the current stack in the future for the sake of learning more about it.  Rails is a much better fit for rapid development and prototyping.

**Comment by mcmillanator** [comment]
I think this is complete.  I might have couple of fields to move around.  I'll double check before closing this out.

**Comment by drewdrew122** [comment]
Accepting issue
