### ISSUE TITLE
"Ambient Before" missing last "e"

### ISSUE THREAD

**Issue by drewdrew122** [racerecords/RaceRecords#3]
(From the email I sent in November)

"Ambient Befor" should be "Ambient Before"

**Comment by mcmillanator** [comment]
# TODO
- [ ] https://github.com/racerecords/jekyll/blame/169b06ce7339f8d68c3d1ca0127bd83c5fcce052/new.md#L63
- [ ] https://github.com/racerecords/jekyll/blame/169b06ce7339f8d68c3d1ca0127bd83c5fcce052/show.md#L57

**Comment by mcmillanator** [comment]
Deprecated code base in favor of a Rails code base
